USE [master]
GO

CREATE DATABASE [WEBSHOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WEBSHOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\WEBSHOP.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WEBSHOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\WEBSHOP_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WEBSHOP] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WEBSHOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WEBSHOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WEBSHOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WEBSHOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WEBSHOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WEBSHOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [WEBSHOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WEBSHOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WEBSHOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WEBSHOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WEBSHOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WEBSHOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WEBSHOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WEBSHOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WEBSHOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WEBSHOP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WEBSHOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WEBSHOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WEBSHOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WEBSHOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WEBSHOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WEBSHOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WEBSHOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WEBSHOP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WEBSHOP] SET  MULTI_USER 
GO

ALTER DATABASE [WEBSHOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WEBSHOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WEBSHOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WEBSHOP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WEBSHOP] SET  READ_WRITE 
GO