USE [WEBSHOP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-------
CREATE TABLE [dbo].[CUSTOMERTYPE](
	[IDTYPE] [tinyint] NOT NULL,
	[TYPEDESCRIPTION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CUSTOMERTYPE] PRIMARY KEY CLUSTERED 
(
	[IDTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------
CREATE TABLE [dbo].[CUSTOMERGENDER](
	[IDGENDER] [tinyint] NOT NULL,
	[GENDERDESCRIPTION] [varchar](25) NOT NULL,
 CONSTRAINT [PK_CUSTOMERGENDER] PRIMARY KEY CLUSTERED 
(
	[IDGENDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------
CREATE TABLE [dbo].[CUSTOMER](
	[CUSTOMERID] [int] NOT NULL,
	[CUSTOMERTYPEID] [tinyint] NOT NULL,
	[BIRTHDATE] [nvarchar](20) NOT NULL,
	[FIRSTNAME] [nvarchar](20) NOT NULL,
	[SECONDNAME] [nvarchar](20) NULL,
	[LASTNAME] [nvarchar](50) NOT NULL,
	[GENDER] [tinyint] NOT NULL,
	[PHONE] [nvarchar](25) NOT NULL,
	[EMAIL] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](50) NOT NULL,
	[CITY] [nvarchar](20) NOT NULL,
	[STATE] [nvarchar](50) NOT NULL,
	[COUNTRY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[CUSTOMERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_GENDER] FOREIGN KEY([GENDER])
REFERENCES [dbo].[CUSTOMERGENDER] ([IDGENDER])
GO

ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_GENDER]
GO

ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_TYPE] FOREIGN KEY([CUSTOMERTYPEID])
REFERENCES [dbo].[CUSTOMERTYPE] ([IDTYPE])
GO

ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_TYPE]
GO

-------
CREATE TABLE [dbo].[CATEGORY](
	[CATEGORYID] [int] NOT NULL,
	[CATEGORYNAME] [nvarchar](25) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
	[STATUS] [bit] NOT NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CATEGORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------
CREATE TABLE [dbo].[PRODUCTSTATUS](
	[PRODUCTSTATUSID] [tinyint] NOT NULL,
	[PRODUCTSTATUSDESCRIPTION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PRODUCTSTATUS] PRIMARY KEY CLUSTERED 
(
	[PRODUCTSTATUSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------
CREATE TABLE [dbo].[PRODUCTS](
	[PRODUCTID] [int] NOT NULL,
	[PRODUCTNAME] [nvarchar](50) NOT NULL,
	[PRODUCTDESCRIPTION] [nvarchar](max) NULL,
	[PRODUCTSTATUS] [tinyint] NOT NULL,
	[MANUFACTURERNUMBER] [nvarchar](50) NOT NULL,
	[SIZE] [nvarchar](30) NOT NULL,
	[COLOR] [nvarchar](50) NULL,
	[HEIGHT] [nvarchar](25) NULL,
	[WIDHT] [nvarchar](25) NOT NULL,
	[WEIGHT] [nvarchar](25) NOT NULL,
	[SHIPPINHWEIGHT] [nvarchar](25) NOT NULL,
	[BRAND] [nvarchar](50) NOT NULL,
	[PACKAGEDIMENSIONS] [nvarchar](50) NOT NULL,
	[UNITPRICE] [decimal](18, 0) NOT NULL,
	[DISCOUNTPRICE] [decimal](18, 0) NOT NULL,
	[UNITSINSTOCK] [int] NOT NULL,
	[UNITSINORDER] [int] NOT NULL,
	[CATEGORYID] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[PRODUCTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTS_CATEGORY] FOREIGN KEY([CATEGORYID])
REFERENCES [dbo].[CATEGORY] ([CATEGORYID])
GO

ALTER TABLE [dbo].[PRODUCTS] CHECK CONSTRAINT [FK_PRODUCTS_CATEGORY]
GO

ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTS_PRODUCTSTATUS] FOREIGN KEY([PRODUCTSTATUS])
REFERENCES [dbo].[PRODUCTSTATUS] ([PRODUCTSTATUSID])
GO

ALTER TABLE [dbo].[PRODUCTS] CHECK CONSTRAINT [FK_PRODUCTS_PRODUCTSTATUS]
GO

-------
CREATE TABLE [dbo].[ORDERDETAILS](
	[ORDERDETAILID] [int] NOT NULL,
	[ORDERID] [int] NOT NULL,
	[PRODUCTID] [int] NOT NULL,
	[ORDERNUMBER] [int] NOT NULL,
	[PRICE] [decimal](18, 0) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[DISCOUNT] [decimal](18, 0) NOT NULL,
	[TOTAL] [decimal](18, 0) NOT NULL,
	[BILLDATE] [date] NOT NULL,
 CONSTRAINT [PK_ORDERDETAILS] PRIMARY KEY CLUSTERED 
(
	[ORDERDETAILID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------
CREATE TABLE [dbo].[ORDERS](
	[ORDERID] [int] NOT NULL,
	[CUSTOMERID] [int] NOT NULL,
	[ORDERNUMBER] [int] NOT NULL,
	[ORDERDATE] [date] NOT NULL,
	[PAYMENTDATE] [date] NOT NULL,
	[PAYMENTID] [int] NOT NULL,
	[SHIPDATE] [date] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[ORDERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_CUSTOMER] FOREIGN KEY([CUSTOMERID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMERID])
GO

ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_CUSTOMER]
GO

ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_ORDERSDET] FOREIGN KEY([ORDERID])
REFERENCES [dbo].[ORDERDETAILS] ([ORDERDETAILID])
GO

ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_ORDERSDET]
GO

CREATE TABLE [dbo].[TESTPRODUCTS](
	[PRODUCTID] [int] NOT NULL,
	[PRODUCTNAME] [nvarchar](50) NOT NULL,
	[PRODUCTSTATUS] [tinyint] NOT NULL,
	[UNITPRICE] [decimal](18, 0) NOT NULL,
	[UNITSINSTOCK] [int] NOT NULL,
CONSTRAINT [PK_TESTPRODUCTS] PRIMARY KEY CLUSTERED 
(
	[PRODUCTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
