//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebshop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAILS
    {
        public int ORDERDETAILID { get; set; }
        public int ORDERID { get; set; }
        public int PRODUCTID { get; set; }
        public int ORDERNUMBER { get; set; }
        public decimal PRICE { get; set; }
        public int QUANTITY { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime BILLDATE { get; set; }
    }
}
