//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebshop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string PRODUCTDESCRIPTION { get; set; }
        public byte PRODUCTSTATUS { get; set; }
        public string MANUFACTURERNUMBER { get; set; }
        public string SIZE { get; set; }
        public string COLOR { get; set; }
        public string HEIGHT { get; set; }
        public string WIDHT { get; set; }
        public string WEIGHT { get; set; }
        public string SHIPPINHWEIGHT { get; set; }
        public string BRAND { get; set; }
        public string PACKAGEDIMENSIONS { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal DISCOUNTPRICE { get; set; }
        public int UNITSINSTOCK { get; set; }
        public int UNITSINORDER { get; set; }
        public int CATEGORYID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PRODUCTSTATUS PRODUCTSTATUS1 { get; set; }
    }
}
