//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebshop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestProducts_Entity
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public byte PRODUCTSTATUS { get; set; }
        public decimal UNITPRICE { get; set; }
        public int UNITSINSTOCK { get; set; }
    }
}
